SVM-THETA  Dense subgraph finding using SVM's 

Copyright (C) 2012  Vinay Jethava <vjethava@gmail.com> 

* Code organization 

This code is organized as follows: 

- src/        	Source code for the jmlr paper. 
- lib/		Third party code. 
- data/		Directory for DIMACS graphs
  
** src/
This directory contains the main implementation and experiments.  Experimental results reported in the paper can be generated by running the scripts. 

- src/ExpMultDimacs.m
- src/ExpPlantedClique.m

*** ExpMultDimacs.m

This script generates the table and figure corresponding to DIMACS graphs. 

*** ExpPlantedClique.m 

This script generates the planted clique figures and table. 

** lib/ 

This directory contains third party code used as part of this project. These must be compiled on test machine for running the main code. We use two main external solvers  described below: 

- lib/libsvm/
- lib/SimpleMKL/ 

*** LIBSVM/ 

LIBSVM is generic SVM solver available from [[http://www.csie.ntu.edu.tw/~cjlin/libsvm/]].

*** SimpleMKL/ 

SimpleMKL is a solver for Multiple Kernel Learning available from [[http://asi.insa-rouen.fr/enseignants/~araakotom/code/mklindex.html]]


** data/ 

The DIMACS dataset can be downloaded from
[[ftp://dimacs.rutgers.edu/pub/challenge/graph/benchmark/clique/]] and 
converted to ascii using converter provided at
[[http://cs.hbg.psu.edu/txn131/file_instances/converter.tar.gz]].
An example of the final ascii file is given below. 

*** data/brock200_1.clq
The file contains the list of edges 

3 2
4 2
...
200 196
200 197
200 199

**** TODO Main script for single run 
**** TODO Meta-script for DIMACS import directly from .tar.gz file
**** TODO Convert to command-line tool
     
* License
    
This program is free software: you can redistribute it and/or modify 
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

